version: '3.8'

services:
  transcribeline:
    container_name: transcribeline
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - HF_TOKEN=${HF_TOKEN} # Load HF_TOKEN from .env file
    volumes:
      - ./data/raw:/app/data/raw
      - ./data/processed:/app/data/processed
      - ./logs:/app/logs
      - ./app/config/settings.toml:/app/config/settings.toml
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
    # --- REMOVE THIS ENTIRE 'command:' SECTION ---
    # command: >
    #   python pipeline.py
    #   /app/data/raw/BU_NI_01_demo_5min.wav
    #   --output-root /app/data/processed
    #   --config /app/config/settings.toml