# version: '3.8'

services:
  transcribeline:
    container_name: transcribeline
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - HF_TOKEN=${HF_TOKEN} # Load HF_TOKEN from .env file
    # user: "${UID}:${GID}" # Load User ID and Group ID from .env file
    volumes:
      - ./data/raw:/app/data/raw
      - ./data/processed:/app/data/processed
      - ./logs:/app/logs
      - ./app/config/settings.toml:/app/config/settings.toml
      - ./whisper_cache:/root/.cache/whisper
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]