[CHUNKING]
max_chunk_duration_sec = 180
min_silence_duration_sec = 1.5

[WHISPER]
model = "large"
language = "pl"

[DIARIZATION]
enabled = true
model = "pyannote/speaker-diarization-3.1"
max_speakers = 2
# token = "moved to .env"

[POSTPROCESSING]
substitutions_file = "config/substitutions.json"

[PARALLEL]
parallel_workers = 1
